baseURL = 'https://example.org/'
languageCode = 'en-us'
title = ' '
theme = 'ananke'
relativeURLs = true
SectionPagesMenu = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 200
  [[menu.main]]
    name = "How to"
    identifier = "howto"
    url = "/categories/howto/"
    weight = 35
  [[menu.main]]
    name = "NUnit"
    url = "/categories/nunit/"
    weight = 10
  [[menu.main]]
    name = "Git"
    identifier = "git"
    url = "/categories/git/"
    weight = 20
  [[menu.main]]
    name = "Course"
    url = "/git/course/"
    weight = 4
    parent = "git"
  [[menu.main]]
    name = "Blogposts"
    url = "/posts/"
    weight = 50
  [[menu.main]]
    name = "Tricks"
    url = "/tricks/"
    weight = 40
  [[menu.main]]
    name = "Principles"
    identifier = "principles"
    url = "/categories/principles/"
    weight = 30
  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 60
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 70



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = "github"

[params]
  date_format = "2006-01-02"
  contentWidth = "max-w-16x1"
  custom_css = ["custom.css","syntax.css","chroma.css"]
  toc = true
  copyright-year = 2009
  mainSections = []

[taxonomies]
  category = "categories"
  tag      = "tags"

[[cascade]]
  [cascade.scope]
    path = "content/git/**"
  [cascade.frontmatter]
    categories = ["git"]

[[cascade]]
  [cascade.scope]
    path = "content/nunit/**"
  [cascade.frontmatter]
    categories = ["nunit"]

[[cascade]]
  [cascade.scope]
    path = "content/how-to/**"
  [cascade.frontmatter]
    categories = ["howto"]

[[cascade]]
  [cascade.scope]
    path = "content/principles/**"
  [cascade.frontmatter]
    categories = ["principles"]

[[cascade]]
  [cascade.scope]
    path = "content/archive/**"
  [cascade.frontmatter]
    categories = ["archive"]